# Generated by Django 2.0.2 on 2018-02-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1),
        ),
    ]
