# Generated by Django 2.0.2 on 2018-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0002_auto_20180208_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
