# Generated by Django 2.0.2 on 2018-02-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0003_auto_20180208_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
