# Generated by Django 2.0.2 on 2018-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0004_practitioner_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_id',
            field=models.CharField(default='5266d83beb9ca0f32b6c6a769555fc0152fe397630c814a23b1346f00e375632', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_salt',
            field=models.CharField(default='d8kHMn5T6h', max_length=255),
        ),
    ]
