# Generated by Django 2.0.2 on 2018-03-07 11:50

import connect_therapy.models
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0008_auto_20180218_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='session_id',
            field=models.CharField(default=functools.partial(connect_therapy.models.generate_session_id, *(), **{'date_time': models.DateTimeField(), 'patient': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_therapy.Patient'), 'practitioner': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect_therapy.Practitioner'), 'salt': models.CharField(default=functools.partial(django.contrib.auth.base_user.BaseUserManager.make_random_password, *(10,), **{}), editable=False, max_length=255)}), editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='session_salt',
            field=models.CharField(default=functools.partial(django.contrib.auth.base_user.BaseUserManager.make_random_password, *(10,), **{}), editable=False, max_length=255),
        ),
    ]
