# Generated by Django 2.0.2 on 2018-03-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0009_auto_20180221_2036'),
        ('connect_therapy', '0009_auto_20180227_2217'),
    ]

    operations = [
    ]
