# Generated by Django 2.0.2 on 2018-03-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0009_auto_20180304_1226'),
        ('connect_therapy', '0009_auto_20180308_1347'),
    ]

    operations = [
    ]
