# Generated by Django 2.0.2 on 2018-03-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0012_auto_20180304_1331'),
        ('connect_therapy', '0009_auto_20180304_1226'),
    ]

    operations = [
    ]
