# Generated by Django 2.0.2 on 2018-03-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0013_merge_20180307_1346'),
        ('connect_therapy', '0009_auto_20180308_1347'),
    ]

    operations = [
    ]
