# Generated by Django 2.0.2 on 2018-03-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0014_merge_20180309_1744'),
        ('connect_therapy', '0009_auto_20180307_1150'),
    ]

    operations = [
    ]
