# Generated by Django 2.0.2 on 2018-03-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0013_auto_20180306_2049'),
        ('connect_therapy', '0015_merge_20180311_1054'),
    ]

    operations = [
    ]
