# Generated by Django 2.0.2 on 2018-03-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0019_auto_20180311_2020'),
        ('connect_therapy', '0010_merge_20180310_1532'),
    ]

    operations = [
    ]
