# Generated by Django 2.0.2 on 2018-03-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0020_merge_20180313_1403'),
        ('connect_therapy', '0020_auto_20180314_1200'),
    ]

    operations = [
    ]
