# Generated by Django 2.0.2 on 2018-03-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0020_auto_20180314_1200'),
        ('connect_therapy', '0025_auto_20180313_2017'),
    ]

    operations = [
    ]
