# Generated by Django 2.0.2 on 2018-03-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0021_merge_20180315_1615'),
        ('connect_therapy', '0026_merge_20180315_2102'),
    ]

    operations = [
    ]
