# Generated by Django 2.0.2 on 2018-03-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0029_auto_20180315_2124'),
        ('connect_therapy', '0021_merge_20180316_1302'),
    ]

    operations = [
    ]
