# Generated by Django 2.0.2 on 2018-03-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0030_merge_20180318_1131'),
        ('connect_therapy', '0032_auto_20180317_2015'),
    ]

    operations = [
    ]
