# Generated by Django 2.0.3 on 2018-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0033_merge_20180318_1801'),
        ('connect_therapy', '0033_merge_20180318_1703'),
    ]

    operations = [
    ]
