# Generated by Django 2.0.2 on 2018-03-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0034_merge_20180319_2025'),
        ('connect_therapy', '0034_merge_20180319_1544'),
    ]

    operations = [
    ]
