# Generated by Django 2.0.3 on 2018-03-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0034_merge_20180319_1535'),
        ('connect_therapy', '0034_merge_20180319_1544'),
    ]

    operations = [
    ]
