# Generated by Django 2.0.2 on 2018-03-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0034_merge_20180319_1535'),
        ('connect_therapy', '0035_merge_20180320_1503'),
    ]

    operations = [
    ]
