# Generated by Django 2.0.3 on 2018-03-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0035_auto_20180319_1513'),
        ('connect_therapy', '0036_auto_20180320_1910'),
    ]

    operations = [
    ]
