# Generated by Django 2.0.3 on 2018-03-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0034_merge_20180319_1557'),
        ('connect_therapy', '0036_auto_20180320_1910'),
    ]

    operations = [
    ]
