# Generated by Django 2.0.3 on 2018-03-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0035_merge_20180320_1234'),
        ('connect_therapy', '0036_merge_20180320_2207'),
    ]

    operations = [
    ]
