# Generated by Django 2.0.3 on 2018-03-22 19:37

import django.contrib.auth.base_user
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0036_auto_20180320_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='session_salt',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='session_id',
            field=models.CharField(default=functools.partial(django.contrib.auth.base_user.BaseUserManager.make_random_password, *(50,), **{}), editable=False, max_length=255),
        ),
    ]
