# Generated by Django 2.0.3 on 2018-03-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0037_merge_20180323_1519'),
        ('connect_therapy', '0037_merge_20180322_1843'),
    ]

    operations = [
    ]
