# Generated by Django 2.0.3 on 2018-03-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0038_auto_20180322_1636'),
        ('connect_therapy', '0038_merge_20180323_2005'),
    ]

    operations = [
    ]
