# Generated by Django 2.0.3 on 2018-03-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0036_auto_20180320_1910'),
        ('connect_therapy', '0038_auto_20180320_2227'),
    ]

    operations = [
    ]
