# Generated by Django 2.0.3 on 2018-03-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0037_auto_20180322_1937'),
        ('connect_therapy', '0038_merge_20180323_1544'),
    ]

    operations = [
    ]
