# Generated by Django 2.0.3 on 2018-03-24 13:09

import django.contrib.auth.base_user
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('connect_therapy', '0039_merge_20180324_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_id',
            field=models.CharField(default=functools.partial(django.contrib.auth.base_user.BaseUserManager.make_random_password, *(50,), **{}), editable=False, max_length=255),
        ),
    ]
